# Generated by Django 4.1.5 on 2023-02-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email_Address', models.EmailField(max_length=254, unique=True)),
                ('DateofBirth', models.DateField()),
                ('Phone_number', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'User_data',
                'verbose_name_plural': 'User_data',
            },
        ),
    ]
