# Generated by Django 4.1.5 on 2023-02-06 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stu_name', models.CharField(blank=True, max_length=50)),
                ('Course', models.CharField(blank=True, max_length=50)),
                ('HOD', models.CharField(max_length=50)),
                ('class_teacher', models.CharField(max_length=50)),
                ('Stu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stu_id', to='students.student')),
            ],
            options={
                'verbose_name': 'Other_info',
                'verbose_name_plural': 'Other_info',
            },
        ),
    ]
