# Generated by Django 4.1.5 on 2023-02-08 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='Stu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
