# Generated by Django 4.1.5 on 2023-02-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('Vedio_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('id', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Youtube_data',
                'verbose_name_plural': 'Youtube_data',
            },
        ),
    ]
